# Generated by Django 6.0.3 on 2026-03-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0002_oadepartment_oauser_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oadepartment',
            old_name='intro',
            new_name='description',
        ),
    ]
