# Generated by Django 6.0.3 on 2026-03-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0003_rename_intro_oadepartment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oadepartment',
            old_name='description',
            new_name='intro',
        ),
    ]
